mmu: mmu.cpp FrameTable.cpp PageReplacementAlgos.cpp VirtualMemoryArea.cpp Utils.cpp Process.cpp PageTableEntry.cpp
	
	g++ -g -std=c++11 mmu.cpp Utils.cpp FrameTable.cpp VirtualMemoryArea.cpp Process.cpp PageReplacementAlgos.cpp PageTableEntry.cpp -o mmu
	
clean:
	
	rm -f mmu *~