sched: sched.cpp DiscreteEventSimulator.cpp EVENT.cpp Scheduler.cpp Utils.cpp Process.cpp
	
	g++ -g -std=c++11 sched.cpp DiscreteEventSimulator.cpp EVENT.cpp Scheduler.cpp Utils.cpp Process.cpp -o sched
	
clean:
	
	rm -f sched *~