schedIO: schedIO.cpp Scheduler.cpp Request.cpp 
	
	g++ -g -std=c++11 schedIO.cpp Scheduler.cpp Request.cpp -o schedIO
# 	g++ -o schedIO -x c++ schedIO.cpp Scheduler.cpp Request.cpp
clean:
	
	rm -f schedIO *~